name: loner
channels:
  - pytorch
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - pip:
    - ConfigArgParse==0.14.0
    - cycler==0.10.0
    - decorator==4.4.0
    - h5py==2.9.0
    - joblib==0.13.2
    - kiwisolver==1.1.0
    - llvmlite==0.28.0
    - matplotlib==3.1.0
    - mock==3.0.5
    - natsort==6.0.0
    - networkx==2.3
    - numba==0.43.1
    - numexpr==2.6.9
    - numpy==1.16.3
    - pandas==0.24.2
    - patsy==0.5.1
    - Pillow==6.0.0
    - pyparsing==2.4.0
    - python-dateutil==2.8.0
    - pytz==2019.1
    - pyyaml==3.13
    - scanpy==1.4.3
    - scikit-learn==0.21.1
    - scipy==1.3.0
    - seaborn==0.9.0
    - six==1.12.0
    - statsmodels==0.9.0
    - tables==3.5.1
    - torch==1.1.0
    - torchvision==0.3.0
    - tqdm==4.32.1
    - umap-learn==0.3.8

